name: build-image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  RELEASE_VERSION: 6.10.1 ## BlockScout Release version

jobs:
  build_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      OTP_VERSION: ${{ vars.OTP_VERSION }}
      ELIXIR_VERSION: ${{ vars.ELIXIR_VERSION }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Tagging
        id: tagging
        run: |
          echo "GIT_TAG=$(echo $TAG_FULL | cut -d'-' -f1)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
          
      - name: Setup Dcocker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build API
        uses: docker/build-push-action@v6
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.ECR_REGISTRY }}/${{ inputs.environment }}/${{ secrets.AWS_ECR_REPO }}-api:${{ steps.tagging.outputs.GIT_TAG }},${{ env.ECR_REGISTRY }}/${{ inputs.environment }}/${{ secrets.AWS_ECR_REPO }}-api:latest
          platforms: linux/amd64
          build-args: |
            DISABLE_INDEXER=true
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}

      - name: Build Indexer 
        uses: docker/build-push-action@v6
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.ECR_REGISTRY }}/${{ inputs.environment }}/${{ secrets.AWS_ECR_REPO }}-indexer:${{ steps.tagging.outputs.GIT_TAG }},${{ env.ECR_REGISTRY }}/${{ inputs.environment }}/${{ secrets.AWS_ECR_REPO }}-indexer:latest
          platforms: linux/amd64
          build-args: |
            DISABLE_API=true 
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}

      # - name: Send release announcement to Slack workflow
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     payload: |
      #       {
      #         "release-version": "${{ env.RELEASE_VERSION }}",
      #         "release-link": "https://github.com/blockscout/blockscout/releases/tag/v${{ env.RELEASE_VERSION }}"
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
