# name: trigger

# on:
#   push:
#     branches: [dev, testnet, master]

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   dev-deploy:
#     if: github.ref == 'refs/heads/dev'
#     uses: ./.github/workflows/common.yml 
#     secrets: inherit
#     with:
#       environment: dev
name: trigger
on:
  push:
    tags:
      - '*dev*'
      - '*release*'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Determine deployment environment
        id: set-env
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ $TAG == *-dev ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          elif [[ $TAG == *-release ]]; then
            echo "environment=testnet" >> $GITHUB_OUTPUT
          else
            echo "No matching environment found"
            exit 1
          fi

      - uses: ./.github/workflows/common.yml
        with:
          environment: ${{ steps.set-env.outputs.environment }}
        secrets: inherit